import {
  ErrorIcon,
  FacebookIcon,
  GithubIcon,
  HiddenPasswordIcon,
  GoogleIcon,
  Logo_Svg,
  NotifyIcon,
  OrDivider,
  SuccessIcon,
  WarningIcon,
  VectorRD,
  RevealHiddenPasswordIcon,
  VectorDown,
  CircleOkay,
  GreenCircleOkay,
  RedCircleWrong,
  CircleQuestionMark,
  PopularOne,
  FacebookPortfolioIcon,
  TwitterIcon,
  LinkedinIcon,
  WhatsappIcon,
  TelegramIcon,
  PrintIcon,
  LinkIcon,
  StorageIcon,
  RAMIcon,
  CPUIcon,
  BandwidthIcon,
  OSIcon,
  IPV4CountIcon,
  EditIcon,
  GreenOkay,
  SearchIcon,
  GrayInfoCircle,
  InfoIcon,
  WebHosting,
  Cloud,
  Server,
  Website,
  Mobile,
  Certficate,
  Seo,
  Security,
  About,
  Blog,
  Portfolio,
  Career,
  Contact,
  NoteIcon,
  ArrowIcon,
  BluePhoneIcon,
  MailIcon,
  LocationIcon,
  GrayFacebookIcon,
  GrayTwitterIcon,
  GrayInstagramIcon,
  GrayLinkedinIcon,
  Check,
  Easier,
  Circle,
  CheckBox,
  LockIcon,
  DragFileIcon,
  Linkedn,
  LiveChat,
  BackIcon,
  UsernameIcon,
  EmailIcon,
  AddressIcon,
  DashboardIcon,
  UploadIcon,
  PasswordIcon,
  MobileIcon,
  NotificationIcon,
  TrashIcon,
  PencilIcon,
  CloseIcon,
  BalanceIcon,
  UserIcon,
  UserProfileIcon,
  LogoutIcon,
  EyeIcon,
  EyeSlashIcon,
  ArrowLeft,
  ArrowRight,
  SettingsIcon,
  PaymentError,
} from "components";
import PropTypes from "prop-types";
import { TbWorldWww } from "react-icons/tb";
import { RiLockPasswordFill } from "react-icons/ri";
import { RxCounterClockwiseClock } from "react-icons/rx";
import { HiServer } from "react-icons/hi";
import { MdAutorenew } from "react-icons/md";
import { BsFillCheckCircleFill, BsFullscreenExit } from "react-icons/bs";
import { FaHome } from "react-icons/fa";
import { IoMdClose } from "react-icons/io";
import { GoListOrdered } from "react-icons/go";

export const Icon = ({ name, ...rest }) => {
  const icons = {
    logo: Logo_Svg,
    or_divider: OrDivider,
    fb_icon: FacebookIcon,
    google_icon: GoogleIcon,
    github_icon: GithubIcon,
    hidden_pass_icon: HiddenPasswordIcon,
    reveal_hidden_pass_icon: RevealHiddenPasswordIcon,
    success_icon: SuccessIcon,
    error_icon: ErrorIcon,
    notify_icon: NotifyIcon,
    warning_icon: WarningIcon,
    vector_rd: VectorRD,
    vector_down: VectorDown,
    circle_okay: CircleOkay,
    green_circle_okay: GreenCircleOkay,
    red_circle_wrong: RedCircleWrong,
    circle_q_mark: CircleQuestionMark,
    popular_one: PopularOne,
    fbportfolio_icon: FacebookPortfolioIcon,
    twitter_icon: TwitterIcon,
    linkedin_icon: LinkedinIcon,
    whatsapp_icon: WhatsappIcon,
    telegram_icon: TelegramIcon,
    print_icon: PrintIcon,
    url_path_icon: LinkIcon,
    storage: StorageIcon,
    ram: RAMIcon,
    cpu: CPUIcon,
    bandwidth: BandwidthIcon,
    os: OSIcon,
    ipv4_count: IPV4CountIcon,
    vps_edit: EditIcon,
    green_okay: GreenOkay,
    search_icon: SearchIcon,
    gray_info_circle: GrayInfoCircle,
    info_icon: InfoIcon,
    web_hosting: WebHosting,
    cloud: Cloud,
    server: Server,
    website: Website,
    domain: TbWorldWww,
    phone: Mobile,
    certificate: Certficate,
    seo: Seo,
    security: Security,
    about: About,
    blog: Blog,
    portfolio: Portfolio,
    career: Career,
    contact: Contact,
    note_icon: NoteIcon,
    arrow_icon: ArrowIcon,
    blue_phone_icon: BluePhoneIcon,
    mail_icon: MailIcon,
    location_icon: LocationIcon,
    gray_facebook_icon: GrayFacebookIcon,
    gray_twitter_icon: GrayTwitterIcon,
    gray_instagram_icon: GrayInstagramIcon,
    gray_linkedin_icon: GrayLinkedinIcon,
    check: Check,
    easier: Easier,
    circle: Circle,
    checkBox: CheckBox,
    lock_icon: LockIcon,
    drag_upload_icon: DragFileIcon,
    linkedn: Linkedn,
    live_chat: LiveChat,
    back_icon: BackIcon,
    username: UsernameIcon,
    email_address: EmailIcon,
    address: AddressIcon,
    dashboard: DashboardIcon,
    upload: UploadIcon,
    password: PasswordIcon,
    mobileIcon: MobileIcon,
    notification: NotificationIcon,
    trashIcon: TrashIcon,
    editIcon: PencilIcon,
    closeIcon: CloseIcon,
    balanceIcon: BalanceIcon,
    userIcon: UserIcon,
    profileIcon: UserProfileIcon,
    logoutIcon: LogoutIcon,
    eyeIcon: EyeIcon,
    eyeSlashIcon: EyeSlashIcon,
    editPasswordIcon: RiLockPasswordFill,
    clockIcon: RxCounterClockwiseClock,
    checkIcon: BsFillCheckCircleFill,
    nsIcon: HiServer,
    renewIcon: MdAutorenew,
    arrow_left: ArrowLeft,
    arrow_right: ArrowRight,
    settingsIcon: SettingsIcon,
    paymentError: PaymentError,
    main: FaHome,
    close_icon: IoMdClose,
    screen_icon: BsFullscreenExit,
    orderList: GoListOrdered,
  };
  const SelectedIcon = icons[name];
  return <SelectedIcon {...rest} />;
};

Icon.propTypes = {
  name: PropTypes.string,
};
