import {
  ErrorIcon,
  Logo_Svg,
  OrDivider,
  SuccessIcon,
  WarningIcon,
  RevealHiddenPasswordIcon,
  VectorDown,
  CircleOkay,
  GreenCircleOkay,
  RedCircleWrong,
  CircleQuestionMark,
  PopularOne,
  EditIcon,
  GreenOkay,
  SearchIcon,
  GrayInfoCircle,
  InfoIcon,
  Contact,
  NoteIcon,
  Check,
  Easier,
  Circle,
  CheckBox,
  LockIcon,
  DragFileIcon,
  BackIcon,
  UsernameIcon,
  EmailIcon,
  AddressIcon,
  DashboardIcon,
  UploadIcon,
  PasswordIcon,
  MobileIcon,
  NotificationIcon,
  TrashIcon,
  PencilIcon,
  CloseIcon,
  UserIcon,
  UserProfileIcon,
  LogoutIcon,
  EyeIcon,
  EyeSlashIcon,
  ArrowLeft,
  ArrowRight,
  SettingsIcon,
} from "components";
import PropTypes from "prop-types";
import { RiLockPasswordFill } from "react-icons/ri";
import { RxCounterClockwiseClock } from "react-icons/rx";
import { HiServer } from "react-icons/hi";
import { MdAutorenew } from "react-icons/md";
import { BsFillCheckCircleFill, BsFullscreenExit } from "react-icons/bs";
import { FaHome } from "react-icons/fa";
import { IoMdClose } from "react-icons/io";
import { GoListOrdered } from "react-icons/go";

export const Icon = ({ name, ...rest }) => {
  const icons = {
    logo: Logo_Svg,
    or_divider: OrDivider,
    reveal_hidden_pass_icon: RevealHiddenPasswordIcon,
    success_icon: SuccessIcon,
    error_icon: ErrorIcon,
    warning_icon: WarningIcon,
    vector_down: VectorDown,
    circle_okay: CircleOkay,
    green_circle_okay: GreenCircleOkay,
    red_circle_wrong: RedCircleWrong,
    circle_q_mark: CircleQuestionMark,
    popular_one: PopularOne,
    vps_edit: EditIcon,
    green_okay: GreenOkay,
    search_icon: SearchIcon,
    gray_info_circle: GrayInfoCircle,
    info_icon: InfoIcon,
    contact: Contact,
    note_icon: NoteIcon,
    check: Check,
    easier: Easier,
    circle: Circle,
    checkBox: CheckBox,
    lock_icon: LockIcon,
    drag_upload_icon: DragFileIcon,
    back_icon: BackIcon,
    username: UsernameIcon,
    email_address: EmailIcon,
    address: AddressIcon,
    dashboard: DashboardIcon,
    upload: UploadIcon,
    password: PasswordIcon,
    mobileIcon: MobileIcon,
    notification: NotificationIcon,
    trashIcon: TrashIcon,
    editIcon: PencilIcon,
    closeIcon: CloseIcon,
    userIcon: UserIcon,
    profileIcon: UserProfileIcon,
    logoutIcon: LogoutIcon,
    eyeIcon: EyeIcon,
    eyeSlashIcon: EyeSlashIcon,
    editPasswordIcon: RiLockPasswordFill,
    clockIcon: RxCounterClockwiseClock,
    checkIcon: BsFillCheckCircleFill,
    nsIcon: HiServer,
    renewIcon: MdAutorenew,
    arrow_left: ArrowLeft,
    arrow_right: ArrowRight,
    settingsIcon: SettingsIcon,
    main: FaHome,
    close_icon: IoMdClose,
    screen_icon: BsFullscreenExit,
    orderList: GoListOrdered,
  };
  const SelectedIcon = icons[name];
  return <SelectedIcon {...rest} />;
};

Icon.propTypes = {
  name: PropTypes.string,
};
